# ==========================================
# C.3 Forge v1 suggestion file
# Generated by tools.forge_suggest.py
# This is a NON-DESTRUCTIVE suggestion.
# Edit and copy changes back into the main file manually.
# Timestamp: 2025-11-20T01:00:57.769224Z
# ==========================================

"""
reasoning/reconcile.py

Reconcile layer for the dual-brain:
- Takes Architect + Oracle outputs
- (Optionally) uses emotional chemicals to adjust temperatures
- Routes decisions between Architect and Oracle
- Returns a ReconcileResult for core.runner

IMPORTANT:
- This function is tolerant to different call styles, e.g.:

    # older style (positional)
    reconcile(confidence, task, architect_output, oracle_output)

    # newer style (keywords)
    reconcile(
        confidence,
        task,
        architect_output=architect_text,
        oracle_output=oracle_text,
        emotions=emotions,
        temperatures=temps,
    )

- All arguments after `confidence` are optional and have defaults,
  so runner can't blow up from "missing argument" or slightly
  different keyword names.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional, Any


@dataclass
class ReconcileResult:
    choice: str            # "architect" or "oracle"
    rationale: str         # runner prints this
    final_text: str
    emotions: Dict[str, float]
    temperatures: Dict[str, float]


def _default_emotions() -> Dict[str, float]:
    """
    Neutral baseline for the four chemicals.
    This is used when the caller does not provide explicit emotions.
    """
    return {
        "dopamine": 0.5,
        "serotonin": 0.5,
        "norepinephrine": 0.5,
        "oxytocin": 0.5,
    }


def _modulate_temperatures(emotions: Dict[str, float]) -> Dict[str, float]:
    """
    Emotion → Temperature Model

    - dopamine       → increases Oracle temp (creativity)
    - norepinephrine → increases Architect temp (focus/sharpness)
    - serotonin      → stabilizer (reduces extremes)
    - oxytocin       → collaboration modifier (slight blend)

    Outputs:
      architect_temperature: float
      oracle_temperature: float
    """

    dopamine = emotions.get("dopamine", 0.5)
    norepi = emotions.get("norepinephrine", 0.5)
    serotonin = emotions.get("serotonin", 0.5)
    oxytocin = emotions.get("oxytocin", 0.5)

    # Base temps
    oracle_temp = 0.4 + (dopamine * 0.4) + (oxytocin * 0.1)
    arch_temp = 0.4 + (norepi * 0.4) - (serotonin * 0.1)

    # Clamp to a safe range
    oracle_temp = max(0.1, min(1.2, oracle_temp))
    arch_temp = max(0.1, min(1.2, arch_temp))

    return {
        "architect_temperature": arch_temp,
        "oracle_temperature": oracle_temp,
    }


def reconcile(
    confidence: float,
    task: Optional[str] = None,
    architect_output: Optional[str] = None,
    oracle_output: Optional[str] = None,
    emotions: Optional[Dict[str, float]] = None,
    temperatures: Optional[Dict[str, float]] = None,
    **kwargs: Any,
) -> ReconcileResult:
    """
    Core reconcile logic.

    - `task` may be None if the caller didn't pass it.
    - `architect_output` / `oracle_output` may be None if older
      code only passed some arguments.
    - `emotions` and `temperatures` are optional; defaults kick in.

    Any extra keyword arguments from the caller are accepted via **kwargs
    so Python never raises "unexpected keyword argument".
    """

    # Normalize outputs so we never format "None"
    if architect_output is None:
        architect_output = "No text provided."
    if oracle_output is None:
        oracle_output = "No text provided."

    # Emotions
    if emotions is None:
        emotions = _default_emotions()
    else:
        emotions = dict(emotions)

    # Temperatures
    if temperatures is None:
        temperatures = _modulate_temperatures(emotions)
    else:
        temperatures = dict(temperatures)

    dopamine = emotions.get("dopamine", 0.5)
    norepi = emotions.get("norepinephrine", 0.5)

    # Score each brain.
    # - Oracle score leans more on dopamine and lower confidence (explore).
    # - Architect score leans more on norepinephrine and higher confidence (exploit).
    oracle_score = dopamine * 0.7 + (1.0 - confidence) * 0.3
    architect_score = norepi * 0.7 + confidence * 0.3

    if oracle_score > architect_score:
        choice = "oracle"
        rationale = (
            "Chose Oracle because creative/emotional state outweighs "
            "confidence in structured reasoning."
        )
        final_text = f"[ORACLE] {oracle_output}"
    else:
        choice = "architect"
        rationale = (
            "Chose Architect because the state favors focus, clarity, "
            "or reliability over exploration."
        )
        final_text = f"[ARCHITECT] {architect_output}"

    return ReconcileResult(
        choice=choice,
        rationale=rationale,
        final_text=final_text,
        emotions=emotions,
        temperatures=temperatures,
    )
