"""
tools/forge_suggest.py

Tiny, safe Forge v1 demo tool.

Usage:
  python3 -m tools.forge_suggest reasoning/reconcile.py

It will:
  - read the target .py file
  - prepend a small Forge header comment
  - write <name>.suggested.py next to it
"""

from __future__ import annotations

import sys
from pathlib import Path
from datetime import datetime


FORGE_HEADER = """# ==========================================
# C.3 Forge v1 suggestion file
# Generated by tools.forge_suggest.py
# This is a NON-DESTRUCTIVE suggestion.
# Edit and copy changes back into the main file manually.
# Timestamp: {timestamp}
# ==========================================

"""


def make_suggestion(source_path: Path) -> Path:
    if not source_path.exists():
        raise FileNotFoundError(f"Source file not found: {source_path}")

    code = source_path.read_text()

    timestamp = datetime.utcnow().isoformat() + "Z"
    header = FORGE_HEADER.format(timestamp=timestamp)

    suggested_code = header + code

    target_path = source_path.with_suffix(source_path.suffix + ".suggested.py")
    target_path.write_text(suggested_code)

    return target_path


def main(argv: list[str] | None = None) -> None:
    if argv is None:
        argv = sys.argv[1:]

    if not argv:
        print("Usage: python3 -m tools.forge_suggest <path/to/file.py>")
        sys.exit(1)

    source = Path(argv[0]).expanduser().resolve()
    print(f"[forge_suggest] Reading: {source}")

    try:
        target = make_suggestion(source)
    except Exception as e:
        print(f"[forge_suggest] ERROR: {e}")
        sys.exit(1)

    print(f"[forge_suggest] Wrote suggestion to: {target}")
    print("[forge_suggest] Done.")


if __name__ == "__main__":
    main()
